config/routes.rb
Rails.application.routes.draw do

  resources :road_buildings

  resources :streets

  resources :categories

  resources :types

  resources :cities

  resources :road_buildings
  resources :annonces

  get 'home/index'
  get 'home/app'
  get 'home/place'

  get 'locations/search' => "locations#place_search"
  get 'locations/count_invite' => "locations#count_invite"
  post 'locations/landing' => "locations#landing"
  post 'locations/search' => "locations#search"
  post 'locations/set_user_favorite_route' => "locations#set_user_favorite_route"
  post 'locations/set_user_favorite_location' => "locations#set_user_favorite_location"
  post 'locations/route_partage' => "locations#route_partage"
  post 'locations/location_partage' => "locations#location_partage"
  get 'locations/search' => "locations#search"
  get 'locations/get_user_routes' => "locations#get_user_routes"
  post 'locations/save_user_route' => "locations#save_user_route"
  post 'locations/save_location' => "locations#save_location"
  get  'locations/getadmin' => "locations#getadmin"
  get  'locations/place' => "locations#place"
  get 'locations/user_locations' => "locations#user_locations"

  get 'locations/get_user_favorite_locations' => "locations#get_user_favorite_locations"
  get 'locations/get_user_suivi_locations' => "locations#get_user_suivi_locations"
  get 'locations/get_user_favorite_routes' => "locations#get_user_favorite_routes"
  get 'locations/get_user_partage_routes' => "locations#get_user_partage_routes"

  post 'locations/filter' => "locations#filter"
  get 'locations/get_user/:id' => "locations#get_user"
  get 'locations/favorite_route' => "locations#favorite_route"
  post 'locations/set_user' => "locations#set_user"
  get 'locations/partage/:id' => "locations#partage"
  get 'locations/user/:id' => "locations#user"
  get 'users/active_user' => "users#active_user"
  resources :locations

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#landing', as: :unauthenticated_root
    end
  end

  get '*path' => redirect('/')
end

app/models/road_building.rb
class RoadBuilding < ActiveRecord::Base
attr_accessor :pid


def pid
   rang = 0
  all = RoadBuilding.where(:road_id => self.road_id)
  all_positive = all.select{|x| x.position.to_i > 0 }
  all_negative = all.select{|x| x.position.to_i < 0 }
  if (self.position.to_i > 0)
    rang = 2*(all_positive.size + 1)
  end
  if(self.position.to_i <= 0 )
      rang = 2*(all_negative.size) + 1
  end
rang
end

def find_or_create_location location
  loc = Location.find_by(:building => location["building"])
  if loc.nil?
  loc = Location.new(location)
  loc.rang = self.pid
  loc.save
  end
  loc
end
def save_place(place , loc_id)
  puts place
  cplace = Place.new(place)
  cplace.location_id = loc_id
  cplace.save
  cplace
end




def attributes
super.merge('pid' => self.pid)
end

end

app/controllers/road_buildings_controller.rb
class RoadBuildingsController < ApplicationController
  before_action :set_road_building, only: [:show, :edit, :update, :destroy]

  respond_to :html , :json

  def index
    @road_buildings = RoadBuilding.all
    respond_with(@road_buildings)
  end

  def show
      respond_with(@road_building)
  end

  def new
    @road_building = RoadBuilding.new
    respond_with(@road_building)
  end

  def edit
  end

  def create
    @road_building = RoadBuilding.new(road_building_params)
    @road_building.save
    #creer une methode sur le model RoadBuilding pour sauvegarder  location
    @location = @road_building.find_or_create_location(location_params)
    @place = @road_building.save_place(place_params, @location.id)
    respond_with(@road_building)
  end

  def update
    @road_building.update(road_building_params)
    respond_with(@road_building)
  end

  def destroy
    @road_building.destroy
    respond_with(@road_building)
  end

  


  private
    def set_road_building
      @road_building = RoadBuilding.find(params[:id])
    end

    def road_building_params
      params.require(:road_building).permit(:road_id, :building_id, :position)
    end
    def location_params
        params.require(:location).permit!
    end
    def place_params
        params.require(:place).permit!
    end

end

app/helpers/road_buildings_helper.rb
module RoadBuildingsHelper
end

app/views/road_buildings/_form.html.erb
<%= form_for(@road_building) do |f| %>
  <% if @road_building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@road_building.errors.count, "error") %> prohibited this road_building from being saved:</h2>

      <ul>
      <% @road_building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :road_id %><br>
    <%= f.number_field :road_id %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.number_field :building_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/road_buildings/edit.html.erb
<h1>Editing road_building</h1>

<%= render 'form' %>

<%= link_to 'Show', @road_building %> |
<%= link_to 'Back', road_buildings_path %>

app/views/road_buildings/index.html.erb
<h1>Listing road_buildings</h1>

<table>
  <thead>
    <tr>
      <th>Road</th>
      <th>Building</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @road_buildings.each do |road_building| %>
      <tr>
        <td><%= road_building.road_id %></td>
        <td><%= road_building.building_id %></td>
        <td><%= road_building.position %></td>
        <td><%= link_to 'Show', road_building %></td>
        <td><%= link_to 'Edit', edit_road_building_path(road_building) %></td>
        <td><%= link_to 'Destroy', road_building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Road building', new_road_building_path %>

app/views/road_buildings/new.html.erb
<h1>New road_building</h1>

<%= render 'form' %>

<%= link_to 'Back', road_buildings_path %>

app/views/road_buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Road:</strong>
  <%= @road_building.road_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @road_building.building_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @road_building.position %>
</p>

<%= link_to 'Edit', edit_road_building_path(@road_building) %> |
<%= link_to 'Back', road_buildings_path %>