config/routes.rb
Rails.application.routes.draw do

  resources :road_buildings

  resources :streets

  resources :categories

  resources :types

  resources :cities

  resources :road_buildings
  resources :annonces

  get 'home/index'
  get 'home/app'
  get 'home/place'

  get 'locations/search' => "locations#place_search"
  get 'locations/count_invite' => "locations#count_invite"
  post 'locations/landing' => "locations#landing"
  post 'locations/search' => "locations#search"
  post 'locations/set_user_favorite_route' => "locations#set_user_favorite_route"
  post 'locations/set_user_favorite_location' => "locations#set_user_favorite_location"
  post 'locations/route_partage' => "locations#route_partage"
  post 'locations/location_partage' => "locations#location_partage"
  get 'locations/search' => "locations#search"
  get 'locations/get_user_routes' => "locations#get_user_routes"
  post 'locations/save_user_route' => "locations#save_user_route"
  post 'locations/save_location' => "locations#save_location"
  get  'locations/getadmin' => "locations#getadmin"
  get  'locations/place' => "locations#place"
  get 'locations/user_locations' => "locations#user_locations"

  get 'locations/get_user_favorite_locations' => "locations#get_user_favorite_locations"
  get 'locations/get_user_suivi_locations' => "locations#get_user_suivi_locations"
  get 'locations/get_user_favorite_routes' => "locations#get_user_favorite_routes"
  get 'locations/get_user_partage_routes' => "locations#get_user_partage_routes"

  post 'locations/filter' => "locations#filter"
  get 'locations/get_user/:id' => "locations#get_user"
  get 'locations/favorite_route' => "locations#favorite_route"
  post 'locations/set_user' => "locations#set_user"
  get 'locations/partage/:id' => "locations#partage"
  get 'locations/user/:id' => "locations#user"
  get 'users/active_user' => "users#active_user"
  resources :locations

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#landing', as: :unauthenticated_root
    end
  end

  get '*path' => redirect('/')
end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
   has_many :attaches, as: :attachable, dependent: :destroy
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]


  respond_to :html , :json
  # GET /annonces
  # GET /annonces.json
  def index
    @annonces = Annonce.all
  end

  # GET /annonces/1
  # GET /annonces/1.json
  def show
  end

  # GET /annonces/new
  def new
    @annonce = Annonce.new
  end

  # GET /annonces/1/edit
  def edit
  end

  # POST /annonces
  # POST /annonces.json
  def create

    @annonce = Annonce.new(annonce_params)
    respond_to do |format|
      if @annonce.save
          unless params[:files].empty?
                params[:files].each do |k,attach|

                @attach = Attach.new
                @attach.filename = change_img_params(attach)
                @attach.attachable = @annonce
                 @attach.save
            end
          end
        format.html { redirect_to @annonce, notice: 'Annonce was successfully created.' }
        format.json { render :show, status: :created, location: @annonce }
      else
        format.html { render :new }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annonces/1
  # PATCH/PUT /annonces/1.json
  def update
    respond_to do |format|
      if @annonce.update(annonce_params)
        format.html { redirect_to @annonce, notice: 'Annonce was successfully updated.' }
        format.json { render :show, status: :ok, location: @annonce }
      else
        format.html { render :edit }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annonces/1
  # DELETE /annonces/1.json
  def destroy
    @annonce.destroy
    respond_to do |format|
      format.html { redirect_to annonces_url, notice: 'Annonce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annonce
      @annonce = Annonce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonce_params
      params[:annonce]
    end
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/views/annonces/_form.html.erb
<%= form_for(@annonce) do |f| %>
  <% if @annonce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annonce.errors.count, "error") %> prohibited this annonce from being saved:</h2>

      <ul>
      <% @annonce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/annonces/edit.html.erb
<h1>Editing annonce</h1>

<%= render 'form' %>

<%= link_to 'Show', @annonce %> |
<%= link_to 'Back', annonces_path %>

app/views/annonces/index.html.erb
<h1>Listing annonces</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annonces.each do |annonce| %>
      <tr>
        <td><%= link_to 'Show', annonce %></td>
        <td><%= link_to 'Edit', edit_annonce_path(annonce) %></td>
        <td><%= link_to 'Destroy', annonce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annonce', new_annonce_path %>

app/views/annonces/new.html.erb
<h1>New annonce</h1>

<%= render 'form' %>

<%= link_to 'Back', annonces_path %>

app/views/annonces/show.html.erb
<p id="notice"><%= notice %></p>

<% @annonce.attaches.each do |attach| %>
  <img src="<%= attach.filename.url %>" />

<% end %>

<%= link_to 'Edit', edit_annonce_path(@annonce) %> |
<%= link_to 'Back', annonces_path %>